name = "Etch"
license = "MIT"
licenselink = "https://github.com/jakechv/etch/blob/master/LICENSE"
description = "Fork of Etch: a lightweight Hugo theme with a focus on content"
homepage = "https://github.com/jakechv/etch"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Jacob Chvatal"
  homepage = "https://jacob.chvatal.com"
